"""Reviewer persona pool for generating authentic-feeling English product reviews.

Personas are designed to match the target audience: Western women aged 40+ interested in spirituality.
"""

PERSONA_POOL: list[dict] = [
    {
        "name": "Margaret",
        "age": 58,
        "location": "Portland, Oregon",
        "occupation": "retired high school teacher",
        "spiritual_background": "intermediate",
        "writing_style": "warm and reflective",
        "pain_points": "seeking purpose after retirement, managing anxiety",
    },
    {
        "name": "Jennifer",
        "age": 45,
        "location": "Austin, Texas",
        "occupation": "yoga instructor",
        "spiritual_background": "advanced",
        "writing_style": "enthusiastic and knowledgeable",
        "pain_points": "deepening spiritual practice, work-life balance",
    },
    {
        "name": "Linda",
        "age": 52,
        "location": "Denver, Colorado",
        "occupation": "corporate HR manager",
        "spiritual_background": "beginner",
        "writing_style": "curious and practical",
        "pain_points": "stress relief, exploring spirituality for the first time",
    },
    {
        "name": "Barbara",
        "age": 63,
        "location": "Savannah, Georgia",
        "occupation": "retired nurse",
        "spiritual_background": "intermediate",
        "writing_style": "gentle and storytelling",
        "pain_points": "grief processing, finding inner peace",
    },
    {
        "name": "Patricia",
        "age": 48,
        "location": "Seattle, Washington",
        "occupation": "UX designer",
        "spiritual_background": "intermediate",
        "writing_style": "analytical and honest",
        "pain_points": "disconnecting from screens, connecting with nature",
    },
    {
        "name": "Susan",
        "age": 55,
        "location": "Nashville, Tennessee",
        "occupation": "small business owner",
        "spiritual_background": "beginner",
        "writing_style": "down-to-earth and warm",
        "pain_points": "entrepreneur burnout, finding balance",
    },
    {
        "name": "Carol",
        "age": 60,
        "location": "Manchester, UK",
        "occupation": "librarian",
        "spiritual_background": "advanced",
        "writing_style": "articulate and thoughtful",
        "pain_points": "health concerns, legacy and meaning",
    },
    {
        "name": "Nancy",
        "age": 42,
        "location": "Toronto, Canada",
        "occupation": "freelance writer",
        "spiritual_background": "intermediate",
        "writing_style": "poetic and emotional",
        "pain_points": "creative block, self-doubt",
    },
    {
        "name": "Deborah",
        "age": 50,
        "location": "Melbourne, Australia",
        "occupation": "psychologist",
        "spiritual_background": "advanced",
        "writing_style": "insightful and professional",
        "pain_points": "compassion fatigue, personal growth",
    },
    {
        "name": "Helen",
        "age": 66,
        "location": "Auckland, New Zealand",
        "occupation": "retired accountant",
        "spiritual_background": "intermediate",
        "writing_style": "meticulous and sincere",
        "pain_points": "staying active in retirement, community connection",
    },
]
